/** Compact UI scale — fits more content on mobile without feeling cramped. */
export const DENSITY = {
    pagePaddingH: 14,
    sectionGap: 12,
    cardRadius: 14,
    cardPadding: 12,
    cardPaddingH: 14,
    listRowPaddingV: 8,
    listRowPaddingH: 12,
    listIcon: 36,
    listIconBadge: 12,
    headerBarHeight: 42,
    avatarHeader: 36,
    iconButton: 32,
    quickActionCircle: 42,
    quickActionIcon: 22,
    quickActionLabel: 10,
    sectionTitle: 14,
    balanceWhole: 26,
    balanceFraction: 15,
    balanceHidden: 26,
    walletCardW: 156,
    walletCardH: 108,
    transactionAvatar: 34,
    profileRowMinH: 46,
    buttonHeight: 42,
    buttonHeightCompact: 34,
    inputHeight: 44,
    searchBarHeight: 36,
    tabBarContent: 42,
    tabBarPaddingTop: 6,
    tabBarLabel: 9,
    actionBtn: 34,
} as const;
