export type RootStackParamList = {
    Onboarding: undefined;
    TabNavigator: undefined;
    Profile: undefined;
    EditPersonalInfo: undefined;
    ExchangeRates: undefined;
    CardMenu: undefined;
    CardDetails: undefined;
    SignIn: { sessionExpired?: string } | undefined;
    SignUp: undefined;
    SignInCode: undefined;
    ChangePassword: undefined;
    ChangePinCode: undefined;
    SignUpAccountCreated: undefined;
    Statistics: undefined;
    StatisticsChooseCard: undefined;
    TopUpPayment: undefined;
    TransactionDetails: undefined;
    TransactionHistory: undefined;
    VerifyYourPhoneNumber: undefined;
    ConfirmationCode: undefined;
    CreateInvoice: undefined;
    FAQ: undefined;
    ForgotPassword: undefined;
    ForgotPasswordSentEmail: undefined;
    FundTransfer: undefined;
    IbanPayment: undefined;
    InvoiceSent: undefined;
    MobilePayment: undefined;
    NewPassword: { resetToken: string };
    OpenMoneybox: undefined;
    OpenNewCard: undefined;
    PaymentFailed: undefined;
    Payments: undefined;
    PaymentSuccess: undefined;
    PrivacyPolicy: undefined;
};
