export type RootStackParamList = {
    TabNavigator: undefined;
    Profile: undefined;
    EditPersonalInfo: undefined;
    SignIn: { sessionExpired?: string } | undefined;
    SignUp: undefined;
    ChangePassword: undefined;
    SignUpAccountCreated: undefined;
    TransactionDetails: { payment?: unknown; paymentId?: string } | undefined;
    TransactionHistory: undefined;
    CreateInvoice: undefined;
    FAQ: undefined;
    ForgotPassword: undefined;
    ForgotPasswordSentEmail: { mode?: string } | undefined;
    InvoiceSent: { payment?: unknown } | undefined;
    NewPassword: { resetToken: string };
    PrivacyPolicy: undefined;
    WalletHelp: undefined;
    AddressBook: undefined;
    WalletSetup: { startAction?: "create" | "import" } | undefined;
    MyWallet: undefined;
    WalletReceive: { network: string; address: string; asset?: "USDT" | "NATIVE" };
};
